### ISSUE TITLE
Cannot read from stdin when using Air

### ISSUE THREAD

**Issue by scarycoffee** [cosmtrek/air#102]
When accessing stdin using `reader := bufio.NewScanner(os.Stdin) etc etc` when the program is running through air, I cannot access the input. However, if I run the program without air, I can access the stdin input.  

Is this an error or something that I am doing wrong?

**Comment by xiantang** [comment]
currently we can‘t access the stdin input...

**Comment by Lomomn** [comment]
It's ok. I have a workaround using a tcp connection. Thank you for the great work.

**Comment by Lomomn** [comment]
Just curious, but why can't stdin be accessed? Is it a limitation of go?

**Comment by xiantang** [comment]
air is use exec.Command to run your application.
and i find a way to access subprocess's stdin. 
```go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	subProcess := exec.Command("go", "run", "./main.go") //Just for testing, replace with your subProcess

	stdin, err := subProcess.StdinPipe()
	if err != nil {
		fmt.Println(err) //replace with logger, or anything you want
	}
	defer stdin.Close() // the doc says subProcess.Wait will close it, but I'm not sure, so I kept this line
	subProcess.Stdin = os.Stdin
	subProcess.Stdout = os.Stdout
	subProcess.Stderr = os.Stderr

	fmt.Println("START")                      //for debug
	if err = subProcess.Start(); err != nil { //Use start, not run
		fmt.Println("An error occured: ", err) //replace with logger, or anything you want
	}
	subProcess.Wait()
	fmt.Println("END") //for debug
}
```
and I will try to add as a feature to air.
it just set subprocess's stdin as `os.stdIn`

**Comment by Lomomn** [comment]
This is great news! Looking forward to it and thank you for your work :)

**Comment by tusharsadhwani** [comment]
any updates on this?
