### ISSUE TITLE
air version is not match

### ISSUE THREAD

**Issue by kindywu** [cosmtrek/air#105]
![image](https://user-images.githubusercontent.com/6177365/90384894-dd508c00-e0b4-11ea-9dbe-e3dcfd81cfda.png)
![image](https://user-images.githubusercontent.com/6177365/90384912-e6d9f400-e0b4-11ea-8910-3d8fb6252d5d.png)

**Comment by xiantang** [comment]
ops. i will release 1.12.4 again...

**Comment by xiantang** [comment]
thank you...

**Comment by kindywu** [comment]
keqi

**Comment by elboletaire** [comment]
Also, in go pkg latest version tagged is `1.21.2` (jumping from 1.12.4).
