### ISSUE TITLE
Remove Ascii art

### ISSUE THREAD

**Issue by Ilyes512** [cosmtrek/air#11]
Is it really required to output this ascii? I would like to see this removed as this just bloats my cli:

```

U  /"\  u       ___      U |  _"\ u
 \/ _ \/       |_"_|      \| |_) |/
 / ___ \        | |        |  _ <
/_/   \_\     U/| |\u      |_| \_\
 \\    >>  .-,_|___|_,-.   //   \\_
(__)  (__)  \_)-' '-(_/   (__)  (__)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If you agree I can make a MR. 😁

**Comment by cosmtrek** [comment]
Sorry, I think this ascii text is so cute that no need to remove it :)

**Comment by Ilyes512** [comment]
It should not be "cute" it should be productive...

I will just fork and make the changes my self.
