### ISSUE TITLE
The .air don't exist

### ISSUE THREAD

**Issue by Johann-Goncalves-Pereira** [cosmtrek/air#110]
![image](https://user-images.githubusercontent.com/62612685/92034173-3ff78800-ed43-11ea-83a6-7625968f45a7.png)

**Comment by xiantang** [comment]
please show your GOPATH by run go env GOPATH. 
and to GOPATH/bin path check air binary is in this path.

**Comment by xiantang** [comment]
my linux server is work well. 
![image](https://user-images.githubusercontent.com/34479567/92093042-6ed63280-ee05-11ea-8023-fbf8c68ca4b3.png)

**Comment by Johann-Goncalves-Pereira** [comment]
I'm solved my problem
