### ISSUE TITLE
Permission denied after update from 1.12.1 to 1.12.3

### ISSUE THREAD

**Issue by kasuskasus1** [cosmtrek/air#113]
Just updated air from 1.12.1 to 1.12.3. Now running `air` in go folder fails as follows:
```
  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.12.3 // live reload for Go apps, with Go1.14.0

watching .
!exclude tmp
building...
running...
/bin/sh: [PATH_TO_FOLDER]/tmp/main: Permission denied
```

**Comment by francismarcus** [comment]
Same here I'm afraid

**Comment by xiantang** [comment]
@kasuskasus1 @francismarcus  which platform did your use？ i cannot reproduce this bug in osx catalina

**Comment by francismarcus** [comment]
@xiantang i'm on catalina 10.15.5.
Not entirely sure what's causing this as it's working in all projects but one, where it has previously worked.

**Comment by kasuskasus1** [comment]
Resinstalled air completely, the issue is now gone.  🤷‍♂️

**Comment by sinnrrr** [comment]
The reinstallation of Air didn't help. Deleted binary from GOPATH, and cleared all caches.

**Comment by sinnrrr** [comment]
That finally worked by itself. The error has gone after reloading the PC.

**Comment by kanopeld** [comment]
On Manjaro linux not working. Relogin and reinstall didn't help. The binary file have not executable permissions for all users

**Comment by kanopeld** [comment]
I've found way: add "&& chmod +x /path/to/bin" to cmd field in build section. That crutch working but need better way

**Comment by bpatyi** [comment]
same error on ubuntu 20.04. :/

**Comment by Git-on-my-level** [comment]
I'm getting this issue now on a fresh install, the executable does not have execute permissions
```
/bin/sh: /Users/dazheng/workspace/go-packages/tmp/main: Permission denied
^Ccleaning...
see you again~
➜  go-packages git:(dz/docker-compose-ci) ✗ ls -la tmp                  
total 8
drwxr-xr-x@  3 dazheng  staff   96 May 26 16:42 .
drwxr-xr-x  30 dazheng  staff  960 May 26 16:39 ..
-rw-r--r--@  1 dazheng  staff  886 May 26 16:42 main
```

Running MacOS 13.3.1
