### ISSUE TITLE
Go 1.15: failed to build

### ISSUE THREAD

**Issue by guyguy333** [cosmtrek/air#114]
Hello,

We did try to update to Go 1.15 but we're having this issue starting air: 

`failed to build, error: fork/exec /bin/sh: Setctty set but Ctty not valid in child`

just after `building...` step. We use Go 1.15 alpine docker image.

Tested with Air v1.12.4

Thanks

**Comment by nickysemenza** [comment]
I fixed this in https://github.com/cosmtrek/air/pull/112, until the maintainers cut a new release i'm pinned to the latest commit in my go.mod (`go get github.com/cosmtrek/air@b538c70423fb3590435c003dda15bf6a2f61187c`)

**Comment by xiantang** [comment]
work is so busy... if i have time will release a new version..

**Comment by Steiniche** [comment]
Just came here to report the same issue.
@xiantang hope you get time to cut a release soon and good luck with the work!

**Comment by HurSungYun** [comment]
same here. wish you have time to release soon 🙏

**Comment by Steiniche** [comment]
@xiantang is there anything we can do to help the process of cutting a new release?

**Comment by cosmtrek** [comment]
@Steiniche @HurSungYun Just release a new version, please check it again :)

**Comment by Steiniche** [comment]
@cosmtrek thank you so much will check it out and report back.

**Comment by Steiniche** [comment]
Hi @cosmtrek I have now tested with go 1.15 and have the following observations

- The docker image is still running with go 1.13, maybe this should be updated?
- `go get github.com/cosmtrek/air` reports a strange version "go: downloading github.com/cosmtrek/air v1.21.2" however it seems like I am getting the latest release which include the changes for this issue

Overall everything works now for go 1.15, thank you so much for taking the time!

**Comment by regmicmahesh** [comment]
any updates?

**Comment by jongear** [comment]
I was able to get my build to pass with `golang:1.16.2` by pinning directly to the latest commit 

`go get github.com/cosmtrek/air@895210e492af4a2dc1c5286e7c4a45cc4d8452a7`

https://github.com/cosmtrek/air/pull/145#issuecomment-803498417

**Comment by arviansetya** [comment]
@cosmtrek i have this problem "failed to build, error: exit status 1"

**Comment by s-jeon-mercury-inc** [comment]
@cosmtrek i have this problem "failed to build, error: exit status 1"
```

#12 4.072 /go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/syscall.go:83:7: undefined: unsafe.Slice
#12 4.072 /go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
#12 4.072 /go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
#12 4.072 note: module requires Go 1.17
------
executor failed running [/bin/sh -c go get -u github.com/cosmtrek/air@v1.21.2]: exit code: 2
build [dev/ctms-backend-auth] failed: exit status 1. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
```

**Comment by s-jeon-mercury-inc** [comment]
`RUN go get github.com/cosmtrek/air@v1.27.8`
