### ISSUE TITLE
why must bin contain ".exe" on windows?

### ISSUE THREAD

**Issue by jroam** [cosmtrek/air#115]
on the windows in .air.toml file

**must like this:**
`
cmd = "go build -o gfdemos.exe"

bin = "./gfdemos.exe"
`

**wrong like this:**
`
cmd = "go build -o gfdemos"

bin = "./gfdemos"
`

Can I use like this always:
`
cmd = "go build -o gfdemos"

bin = "./gfdemos"
`

Thinks!

**Comment by xiantang** [comment]
sorry... i not have window environment.could you send a pr? i will check it.

**Comment by chjiyun** [comment]
Just like this:
```
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
```
