### ISSUE TITLE
Support default config file path

### ISSUE THREAD

**Issue by trevoro** [cosmtrek/air#120]
When running air you *must* specify the config file even though one may be present in the cwd.
I'd like to suggest we look at reading the `.air.toml` file if it's present by default and using that if the `-c` flag is not passed. It's just a few more lines of code to set the default and I'd be happy to write the PR. This way you can just run `air` without having to type in the config path every time.

**Comment by datoga** [comment]
@trevoro Reading the documentation is like you said, but I have the same issue, I have to pass the `-c `flag with the configuration file although my config file is `.air.toml`.

**Comment by cosmtrek** [comment]
@trevoro @datoga What's your project layout?

**Comment by superhawk610** [comment]
I ran into this same issue and realized that I was actually using an old version of `air`, double check #133 and see if that's the case for you as well.
