### ISSUE TITLE
how to ignore golang test files

### ISSUE THREAD

**Issue by axiaoxin** [cosmtrek/air#127]
try to set exclude_file = ["*_test.go"]
but not work

**Comment by rizalgowandy** [comment]
I think this is a great addition.

**Comment by xiantang** [comment]
we try to add this feature. support regex in exclude files

**Comment by SuzurikawaChihiro** [comment]
@xiantang 
I was in trouble because the test code was also hot reloaded
Is it okay if I do this task?

**Comment by xiantang** [comment]
yeah PR is welcom！

硯川 千優 Suzurikawa ***@***.***>于2021年5月17日 周一00:55写道：

**Comment by SuzurikawaChihiro** [comment]
@axiaoxin 
> try to set exclude_file = ["*_test.go"]
> but not work

this try it `exclude_file = ["_test.go"]`

**Comment by xiantang** [comment]
exclude_file = ["_test.go"]

**Comment by xiantang** [comment]
close ...
