### ISSUE TITLE
'go get' installs old version

### ISSUE THREAD

**Issue by HeCorr** [cosmtrek/air#133]
On Windows 10, installing Air through the `go get -u github.com/cosmtrek/air` command installs the version `1.12.1` instead of the latest `1.15.1`.

**Comment by HeCorr** [comment]
...I guess this explains all the issues I've been facing

**Comment by HeCorr** [comment]
it appears to be installing off of an inexistent tag:

```
$ go get -u github.com/cosmtrek/air

go: github.com/cosmtrek/air upgrade => v1.21.2
[...]
```

I think `1.21.2` was a typo of `1.12.1` which got renamed later but is still in effect somehow, and since 21 > 15 it installs that over `1.15.1`...

**Comment by jim** [comment]
I ran into this on macOS today as well- using `go get` installed 1.12.1. Using the alternative install for macOS did install 1.15.1.

**Comment by superhawk610** [comment]
@HeCorr is right, it looks like `v1.12.2` was accidentally pushed to the tag `v1.21.2` as well, which is more recent in semver than `1.15.1`, the _actual_ latest version. Since you cannot remove a specific version from the package registry (pkg.go.dev), I believe the fix is to publish a copy of `v1.15.1` and tag it `v1.21.3`.

**Comment by uta-mori** [comment]
I ran into this on macOS today as well

Since go1.16, the version can be specified in go install, so the following worked for me

How can I solve this problem fundamentally?
next Release 1.21.3?

```
FROM golang:1.16-buster AS dev
WORKDIR /app
COPY . .
RUN go install github.com/cosmtrek/air@v1.15.1
CMD air
```

**Comment by superhawk610** [comment]
@uta-mori correct, once the repository owner publishes the corrected tag, you should be able to just use `go get` without specifying the version.

**Comment by HeCorr** [comment]
He's alive! :)
