### ISSUE TITLE
Air stuck after rebuilding Docker image or changing files

### ISSUE THREAD

**Issue by emilhakobian** [cosmtrek/air#134]
I'm having trouble with live reload for my go application running on docker. There are two cases. 
1. I start the docker(or reload) and air start to watching files in my directory, but after changing any file it stuck on building forever. 

<img width="404" alt="image" src="https://user-images.githubusercontent.com/4651893/102691283-bf429600-4224-11eb-9658-335278c189f3.png">

2. I rebuild the image and via docker-compose and it stuck on a certain directory.
<img width="735" alt="image" src="https://user-images.githubusercontent.com/4651893/102690493-36752b80-421f-11eb-97bc-2ad5511c41c2.png">

**Comment by aibolorazbekov** [comment]
The same problem with Docker 3.0.0 version.

**Comment by aibolorazbekov** [comment]
Found the solution:
1. Open Docker desktop Preferences -> Experimental Features
2. Switch on Use gRPC FUSE for file sharing option.
