### ISSUE TITLE
zsh: command not found: air

### ISSUE THREAD

**Issue by scratchoo** [cosmtrek/air#135]
tried to installed air using both 

`go get -u github.com/cosmtrek/air`

and 

`curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin`

then added alias air='~/.air'  to .zshrc file
sourced the .zshrc (even restarted the terminal)

then run `air -c .air.toml` 

`zsh: no such file or directory: /home/mee/.air`

system: ubuntu 18.04

**Comment by shadwan** [comment]
same issue, on m1 mac

**Comment by rizalgowandy** [comment]
That's expected.

# binary will be $(go env GOPATH)/bin/air
`curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b `

Meanwhile, your alias is pointing to `~/.air`
The binary isn't there.

You should update your alias to alias air='$(go env GOPATH)/bin/.air'
or move the binary to your home directory.
`mv $(go env GOPATH)/bin/.air ~/.air`

**Comment by NLeRoy917** [comment]
What @rizalgowandy said ^

My binary got installed in /Users/your-username/go/bin/air

**Comment by tedoham** [comment]
> That's to be expected.
> Executing `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b `.
> Binary will be `$(go env GOPATH)/bin/air`.
> Meanwhile, your alias is pointing to `~/.air`.
> The binary isn't there.
> 
> Your choices:
> 
> 1. Update your alias to `alias air='$(go env GOPATH)/bin/.air'`
> 2. Move the binary to your home directory. `mv $(go env GOPATH)/bin/.air ~/.air`

It works for me after I removed "." -> alias air='$(go env GOPATH)/bin/air'

**Comment by Petercopter** [comment]
Go noob here, same problem. I installed both using the installer, and also with `go get` while I was thrashing around. I wanted to keep it under version control, so I deleted the installed version and went with the `go get` method. It looks like

```
alias air='$(go env GOPATH)/bin/air'
```
Works for either one?

**Comment by xiantang** [comment]
> That's to be expected.
> Executing `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b `.
> Binary will be `$(go env GOPATH)/bin/air`.
> Meanwhile, your alias is pointing to `~/.air`.
> The binary isn't there.
> 
> Your choices:
> 
> 1. Update your alias to `alias air='$(go env GOPATH)/bin/air'`
> 2. Move the binary to your home directory. `mv $(go env GOPATH)/bin/air ~/.air`

this one is the solution. close...

**Comment by JVmano** [comment]
> That's to be expected. Executing `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b `. Binary will be `$(go env GOPATH)/bin/air`. Meanwhile, your alias is pointing to `~/.air`. The binary isn't there.
> 
> Your choices:
> 
> 1. Update your alias to `alias air='$(go env GOPATH)/bin/air'`
> 2. Move the binary to your home directory. `mv $(go env GOPATH)/bin/air ~/.air`

It's 

> > That's to be expected.
> > Executing `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b `.
> > Binary will be `$(go env GOPATH)/bin/air`.
> > Meanwhile, your alias is pointing to `~/.air`.
> > The binary isn't there.
> > Your choices:
> > 
> > 1. Update your alias to `alias air='$(go env GOPATH)/bin/.air'`
> > 2. Move the binary to your home directory. `mv $(go env GOPATH)/bin/.air ~/.air`
> 
> It works for me after I removed "." -> alias air='$(go env GOPATH)/bin/air'

Nice! Inserting this alias in bashrc or zshrc makes any terminal session definitive for those who don't already know

**Comment by gabr0236** [comment]
> 

This works for me. But every time i close/reopen i need to set the alias. Is there a more permanent option?

**Comment by JVmano** [comment]
@gabr0236 Check if there's any other path to your bashrc/zshrc. As always the default path is in **~/**.

Some of those topics can be useful:
https://askubuntu.com/questions/160789/aliases-dont-work-after-restart-terminal
https://stackoverflow.com/questions/53270978/bash-alias-disappears-when-opening-new-terminal

**Comment by dhiashalabi** [comment]
> tried to installed air using both
> 
> `go get -u github.com/cosmtrek/air`
> 
> and
> 
> `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin`
> 
> then added alias air='~/.air' to .zshrc file sourced the .zshrc (even restarted the terminal)
> 
> then run `air -c .air.toml`
> 
> `zsh: no such file or directory: /home/mee/.air`
> 
> system: ubuntu 18.04

You will need to update your `~/.zshrc` file by adding this line:
`export PATH=$PATH:$(go env GOPATH)/bin`

**Comment by maprangsoft** [comment]
> > Go noob here, same problem. I installed both using the installer, and also with `go get` while I was thrashing around. I wanted to keep it under version control, so I deleted the installed version and went with the `go get` method. It looks like
> > ```
> > alias air='$(go env GOPATH)/bin/air'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Works for either one?
> 
> This need to be updated on doc

thank you very much this working for me.

**Comment by FlavioScimeca** [comment]
just for the noobs like me :) , after you add the alias in your .zshrc or .bashrc make sure u kill the terminal and open a new one

**Comment by yahya-aghdam** [comment]
Just add the `alias` to `bashrc` and restart it

1. Open the `bashrc` file:
```bash
nano ~/.bashrc
```

2. Add this to the end of file and save it:
`alias air='$(go env GOPATH)/bin/air'`

3. Restart `bashrc` file:
```bash
source ~/.bashrc
```

**Comment by AbdelrahmanAbounida** [comment]
u can download it like that 

`curl -sSfL https://goblin.run/github.com/air-verse/air | sh`

and then refresh your terminal

**Comment by Jijun-TANG** [comment]
Hello, in my case (Mac m1), air is installed using `go install github.com/air-verse/air@latest` and it is put under `/Users/<username>/go/bin/air` and you have to point your alias to this location. Hope that help someone.

**Comment by pnlinh** [comment]
> > > Go noob here, same problem. I installed both using the installer, and also with `go get` while I was thrashing around. I wanted to keep it under version control, so I deleted the installed version and went with the `go get` method. It looks like
> > > ```
> > > alias air='$(go env GOPATH)/bin/air'
> > > ```
> > > 
> > > 
> > >     
> > >   
> > > Works for either one?
> > 
> > 
> > This need to be updated on doc
> 
> i add to .zshrc thank you very much this working for me.
@yahya-aghdam thanks a lot
