### ISSUE TITLE
Process not being killed on Windows

### ISSUE THREAD

**Issue by HeCorr** [cosmtrek/air#147]
Hello! First of all, thank you for this awesome package  :)

Due to Air's current implementation of starting processes on Windows (with `start /b`), the PID returned by `cmd.Process.Pid` is of a process that already exited (`start`'s PID, not what it started), hence the debug error `failed to kill PID ###, error: exit status 128` is returned.

When trying to run the `TASKKILL` command manually, I noticed the following error: `ERROR: The process "###" was not found.`, which confirms my suspicion.

I'm thinking of a good way to fix this, since just `TASKKILL`ing the process by name isn't a good idea.

Is `start /b` even necessary? I'll try to modify the code and run some tests without it.

If that doesn't work, maybe try to get the PID by executable path? Is that even possible? If so, just check it against `c.Build.FullBin` and use that on `TASKKILL`.

I don't think it would be a good idea to try to parse `TASKLIST` as the language might change per system, etc. (also it doesn't even seem to return the executable path).. but I don't see other alternatives as listing processes in Go [seems to be a nightmare](https://stackoverflow.com/a/46849516)..

Suggestions?

**Comment by HeCorr** [comment]
This might be what we want:  https://stackoverflow.com/a/51319981

**Comment by HeCorr** [comment]
I tried using `start /WAIT /B` but although Air doesn't show an error anymore when killing it, the process is still running.

**Comment by HeCorr** [comment]
I figured it out! After hours of investigation!

So, it turns out there were two issues:

1. What prevented the process from being killed was indeed the lack of the `/wait` in the `start /b` call.
2. What made me think that adding `/wait` didn't fix it is that there's actually a sort of race condition where the program will end right before `e.killCmd(cmd)` has a chance to do anything, and I didn't notice that at first because I was using `Ctrl + C` instead of triggering a reload. I verified this by adding two prints right above and below `e.killCmd()`, and as I guessed, only the first one was printed. Another test I did was adding `time.Sleep(time.Second)` to the very end of `main()` and it did the trick!

The first issue was already fixed, I'll send a PR later. The second one will require a bit more thinking as I need to send an "ok to exit" signal to `main()` so it waits for the process to be killed before exiting.

If that's the only goroutine I need to wait for I might just use a channel, otherwise I'l have to use wait groups.

**Comment by tusharsadhwani** [comment]
Hey @HeCorr, can you also verify if #122 is not an issue anymore? I haven't been using it lately. If it's not an issue i'll just close the PR.

**Comment by chjiyun** [comment]
```
[GIN-debug] [ERROR] listen tcp :3000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
cleaning...
deleting E:\WorkPlace\gin_app\tmp
failed to delete tmp dir, err: remove E:\WorkPlace\gin_app\tmp\main.exe~: Access is denied.
see you again~
```

i  don't know why the main.exe~  always appears in the ./tmp

**Comment by HeCorr** [comment]
@tusharsadhwani That doesn't happen in my current setup, but I do remember seeing this `C:\...\C:\...\main.exe` bug before. I'll run some tests and get back to you  :)

**Comment by HeCorr** [comment]
@chjiyun That's the same error I was having (I forgot to mention it), but with Fiber. It couldn't restart as the port was still in use.

I think `main.exe~` is created by the `go build` command, when it tries to overwrite the original `main.exe` file, but it can't because it's still running, so it writes to `main.exe~` instead. (that's my guess)

If they merge my PR the issue will be fixed.

If you need the patch now:

`git clone https://github.com/HeCorr/air`
`cd air`
`git checkout win-kill-fix`
`go install`

**Comment by HeCorr** [comment]
@tusharsadhwani sorry for the delay. unfortunately it looks like the path issue still exists.

You can, however, get around it by using a config file.

**Comment by EnzoTools** [comment]
> @tusharsadhwani sorry for the delay. unfortunately it looks like the path issue still exists.
> 
> You can, however, get around it by using a config file.

I also encountered the same problem:
`failed to kill PID 10124, error: exit status 255`

Thank you very much for the patch you provided

**Comment by EnzoTools** [comment]
> @tusharsadhwani That doesn't happen in my current setup, but I do remember seeing this `C:\...\C:\...\main.exe` bug before. I'll run some tests and get back to you :)

**After I solved [#147](https://github.com/cosmtrek/air/issues/147) PR, [#122](https://github.com/cosmtrek/air/pull/122) the problem still exists, It needs to be fixed**

`building...
trying to kill cmd [cmd /c D:\goProject\src\GoBlog\tmp\main.exe]
cmd killed, pid: 7420
failed to remove D:\goProject\src\GoBlog\tmp\main.exe, error: remove D:\goProject\src\GoBlog\D:\goProject\src\GoBlog\tmp\main.exe: The
 filename, directory name, or volume label syntax is incorrect.
event: "D:\\goProject\\src\\GoBlog\\tmp": WRITE
running...
event: "D:\\goProject\\src\\GoBlog\\tmp": WRITE

**Comment by HeCorr** [comment]
Just so you know I found another panic on my PR and still gotta fix it (it happens when a build fails and a reload is triggered).

If you want me to, I can create a branch on my fork that has both issues solved, since it looks like this repo is abandoned.

**Comment by tusharsadhwani** [comment]
@HeCorr sounds great, but why a separate branch? does it not work on some platform?

**Comment by HeCorr** [comment]
@tusharsadhwani I gotta create a separate branch for both issues so one doesn't conflict with eachother's PRs.

This branch will be for personal use (manual patching), not for merging.

**Comment by HeCorr** [comment]
Alright, I created a branch with both #122 and #147 patches.  :)

Installation steps:
`git clone -b win-fixes https://github.com/HeCorr/air`
`cd air`
`go install`

**Comment by EnzoTools** [comment]
Sorry, I don't understand why you create another branch.
Is the repo deprecated?

**Comment by xiantang** [comment]
> Alright, I created a branch with both #122 and #147 patches. :)
> 
> Installation steps:
> `git clone -b win-fixes https://github.com/HeCorr/air`
> `cd air`
> `go install`

i have a windows system now. i will check this pr
