### ISSUE TITLE
Can share a sample config.yml for Windows?

### ISSUE THREAD

**Issue by hyp530** [cosmtrek/air#149]
2021/03/07 11:32:30 [Setting] config error:  open ../config/config.yml: The system cannot find the path specified.
2021/03/07 11:32:30 [Setting] Config init success

I failed to run it on WIndows. It's asking for config.yml. Can anyone share a sample config file? Thanks in advance.

**Comment by HeCorr** [comment]
Hello! First of all, which version of Air are you using?

Please make sure you're on the latest one by running `go install github.com/cosmtrek/air@v1.15.1`.

**Comment by xiantang** [comment]
use `air init` . close...
