### ISSUE TITLE
Use default config if not in .air.conf file.

### ISSUE THREAD

**Issue by frederikhors** [cosmtrek/air#15]
Can we use default config if not specified in .air.conf file?

Example:

air works great without config file, just use air in my cmd and everything works.
But I need to disable time so I create a new file `.air.conf` with just:

```
[log]
time = false
```

in it. Now calling again air doesn't work. It gives an error:

`PANIC: runtime error: invalid memory address or nil pointer dereference`

I'm on Windows, air installed with `go get -u github.com/cosmtrek/air`

**Comment by cosmtrek** [comment]
Thanks for your advice. First, I need to fix panic if conf file is invalid. Then I will consider it.

**Comment by cosmtrek** [comment]
@frederikhors I've addressed this problem in the newly released version just now. Could you have a try?

**Comment by frederikhors** [comment]
Yes it works now. No more panic error.
