### ISSUE TITLE
air fails to build when using `go install` in golang1.16

### ISSUE THREAD

**Issue by bellwood4486** [cosmtrek/air#150]
## Summary

air fails to execute a process, when setting up with `go install`
```Dockerfile
FROM golang:1.16-alpine
# ...snip...
RUN go install github.com/cosmtrek/air@latest
# ...snip...
```

But air works, when doing with `go get`
```Dockerfile
FROM golang:1.16-alpine
# ...snip...
RUN go get -u github.com/cosmtrek/air
# ...snip...
```

## How to reproduce

I made a sample to reproduce the problem.
https://github.com/bellwood4486/sample-air-error

1. Please clone the sample repository.
2. Run the following commands.
```shell
make build
make run
```

## Result

air fails to execute a process.
```
  __    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ v1.12.1 // live reload for Go apps, with Go1.14.0

watching .
!exclude tmp
building...
failed to build, error: fork/exec /bin/sh: Setctty set but Ctty not valid in child
```

**Comment by HeCorr** [comment]
As noted in #133, the `air@latest` tag is mistakenly being redirected to the old `1.12.1` version, instead of the actual latest, `1.15.1`, which appears to be your case.

Please change your command to `RUN go install github.com/cosmtrek/air@1.15.1` and try again.

**Comment by bellwood4486** [comment]
Hi, @HeCorr 
Thank you for your response. I have tried with the following command. air works fine!
`RUN go install github.com/cosmtrek/air@v1.15.1`

**Comment by HeCorr** [comment]
great to hear!

please proceed to close the issue if you think everything is working as expected  :)

**Comment by bellwood4486** [comment]
In my opinion, it would be better to make the version up to 1.21.0 a missing number.
Because this problem will not go away until the version is 1.22.0.

What do you think about the idea of making it a missing number?

**Comment by bellwood4486** [comment]
Hi, @cosmtrek !
I hope you will consider the above comment when you put the next version.
Thank you.

**Comment by HeCorr** [comment]
If by "missing number" you mean skipping a few versions and releasing the next one as `v1.22.0`, yeah that's what they should do

**Comment by jongear** [comment]
I've also ran into issues with running the latest release of air with `golang:1.16.2`

`Dockerfile`
```dockerfile
FROM golang:1.16.2

RUN apt update \
    && apt upgrade -y \
    && apt install -y git \
    && go get github.com/cosmtrek/air
```

output
```
  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.12.1 // live reload for Go apps, with Go1.14.0

mkdir /app/tmp/tmp
watching .
!exclude tmp
building...
failed to build, error: fork/exec /bin/sh: Setctty set but Ctty not valid in child
```

I found if I pin my `go get` to the latest commit it works fine though

```dockerfile
FROM golang:1.16.2

RUN apt update \
    && apt upgrade -y \
    && apt install -y git \
    && go get github.com/cosmtrek/air@895210e492af4a2dc1c5286e7c4a45cc4d8452a7
```
