### ISSUE TITLE
I want to output .air.toml from cli.

### ISSUE THREAD

**Issue by dohq** [cosmtrek/air#153]
Hi.
Thank you for the great useful tool!

 it might be useful to be able to output the sample configuration file from the command.
This tool works broadly ideal even without a configuration file.
So, in the rare case that you need a configuration file,
you will need to copy and paste the file from github every time or remember which project the existing configuration file was used in.
Fortunately, they seem to be using go1.16 these days, so I used embed to embed air_example.toml.
https://github.com/dohq/air/commit/a1cffeef80815764598833f4dbbc0aa6aa50ca98

If you are okay with adding this feature, create a pull request.
Cheers!

**Comment by cosmtrek** [comment]
@dohq Seems great, could you create a pr?
