### ISSUE TITLE
temp folder cannot be deleted when exiting

### ISSUE THREAD

**Issue by tomaswarynyca** [cosmtrek/air#154]
Hi, in config file i have `clean_on_exit = true` but on exits the folder is not eliminated

**Comment by davidedpg10** [comment]
I know this has been closed for a while, but I am experiencing the same issue. Did you ever find a solution for it?

**Comment by davidedpg10** [comment]
I should clarify. Running it in a docker container, so when it's left behind I cannot delete the folder from my host machine because it's technically owned by a container
