### ISSUE TITLE
No version number printed

### ISSUE THREAD

**Issue by c9845** [cosmtrek/air#157]
On latest air 1.26.0 release, go 1.16.3, when running `air -v` no version is printed out for `air` nor for `golang`.  Looks to be an issue with the Makefile setting the variables accordingly via `LDFLAGS` lines upon building of the release.  Tested on Windows 10, WSL, and Ubuntu 20.04.

**Comment by cosmtrek** [comment]
I'll fix it~

**Comment by cosmtrek** [comment]
Please use `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin` to install air.

**Comment by xiantang** [comment]
i have  a proposal. 
when we want release a version.
use `make tag v1.xx.x` to add git tag and create a file 
version.txt
```
v1.xx.x
```
then add this file to version control system(git)
and use `git push origin v1.xx.x` to release this version.
when we use `air version` 
just use `go embed` feature to inject version to code...

**Comment by xiantang** [comment]
use https://github.com/cosmtrek/air#prefer-installsh to install
