### ISSUE TITLE
[feature request] should us support other  program language? like php?

### ISSUE THREAD

**Issue by xiantang** [cosmtrek/air#165]
#89 
#141
We have received the above questions and hope to discuss the benefits of multilingual support with the community...

**Comment by andrei-dascalu** [comment]
As a PHP developer I don't quite see the benefit. What would Air do in practice? In a development environment you shouldn't need to restart servers or anything (maybe refresh browser?)

I do see the benefit of it in a modern environment like Roadrunner, but Roadrunner itself (Go-base) allows for hot-reload. Swoole also already supports it (https://www.swoole.co.uk/docs/modules/swoole-server-reload)
Typescript/JS devs already have the tooling for it, though if Air can somehow do it easier ... that would be great.

**Comment by makiuchi-d** [comment]
How about using [arelo](https://github.com/makiuchi-d/arelo)?
It can reload any command line tool, even if that is a browser controlling script.
