### ISSUE TITLE
air‘s hot reboot still not work ,on win10 amd64 vscode  go1.16。

### ISSUE THREAD

**Issue by kindywu** [cosmtrek/air#167]
it still not work ,win10 vscode  go1.16。

building...
failed to remove D:\WS\go\demo1\tmp\main.exe, error: remove D:\WS\go\demo1\D:\WS\go\demo1\tmp\main.exe: The filename, directory name, or volume label syntax is incorrect.
running...

![image](https://user-images.githubusercontent.com/6177365/116176064-0ea15180-a744-11eb-8ae8-e4d613ccdd91.png)

![image](https://user-images.githubusercontent.com/6177365/116175801-963a9080-a743-11eb-98de-c0a4d440084a.png)

demo source 
[demo1.zip](https://github.com/cosmtrek/air/files/6381480/demo1.zip)

_Originally posted by @kindywu in https://github.com/cosmtrek/air/pull/122#issuecomment-827267110_

**Comment by xiantang** [comment]
fixed.

**Comment by xiantang** [comment]
i release new version now

**Comment by xiantang** [comment]
![image](https://user-images.githubusercontent.com/34479567/116254908-548e0200-a7a4-11eb-8924-fe3b690eb1f2.png)
![image](https://user-images.githubusercontent.com/34479567/116255086-8010ec80-a7a4-11eb-89e3-7cfa9e992a06.png)
@kindywu 
in v1.27.3 reload is fixed.. plz update air version to 1.27.3 
use https://github.com/cosmtrek/air#prefer-installsh

**Comment by xiantang** [comment]
close...

**Comment by kindywu** [comment]
great!!!!
