### ISSUE TITLE
panic: listen tcp 0.0.0.0:8000: bind: address already in use

### ISSUE THREAD

**Issue by Astrolx** [cosmtrek/air#168]
I use macos,when I exit air then cmd air,the error was appeared

**Comment by SuzurikawaChihiro** [comment]
Me Too
![image](https://user-images.githubusercontent.com/64934951/118746818-dfd65100-b893-11eb-99cb-be4747049df6.png)

**Comment by RajivSah** [comment]
me too +1

**Comment by zyxlcr** [comment]
me too +1 
use mac

**Comment by winston0410** [comment]
Same issue as well, even I have set `send_interrupt = true`

**Comment by c2rad** [comment]
Seems like I found a workaround by setting kill_delay to 0.  Anecdotally, I think you need to restart air to get it to read in config changes.
```
kill_delay = 0 # ms

**Comment by makiuchi-d** [comment]
Air's process management  is incomplete, and in rare cases sub-processes cannot be stopped.
The `send_interrupt` is not working as in the issue #129.

Please try [arelo](/makiuchi-d/arelo). It may work fine.

**Comment by xiantang** [comment]
for mac. I have released 1.27.5 for this. can try it
