### ISSUE TITLE
Can not print console log properly

### ISSUE THREAD

**Issue by cyhhao** [cosmtrek/air#17]
System : MacOS 10.14.2 
Air version: v1.10

-----------
I try to print in many ways, like this:
![image](https://user-images.githubusercontent.com/5381613/51465520-060e8380-1da3-11e9-8acd-b551ffe950a3.png)

Start in normal:
![image](https://user-images.githubusercontent.com/5381613/51465846-b8464b00-1da3-11e9-941b-479668d26903.png)
It can print all of log.

Use air to start:
![image](https://user-images.githubusercontent.com/5381613/51465875-c85e2a80-1da3-11e9-9bd0-0a8ff3ea205c.png)

The log seems to be printed randomly.

**Comment by cosmtrek** [comment]
It seems wired. I'll take time to look into it.

**Comment by thenomemac** [comment]
I'm also seeing out of order and dropped logging on Arch linux.

**Comment by cosmtrek** [comment]
@thenomemac Thanks, it may be related with pty. Currently, I'm busy working and have no time to fix it. Sorry for this bug.

**Comment by thenomemac** [comment]
NP totally get the business. Great project. Keep up the good work when you
get to it. Or I may get to it sometime. But.. Ya work too.

**Comment by renatosuero** [comment]
@cosmtrek I don't know if it can be useful to you.  I commented this [line](https://github.com/cosmtrek/air/blob/master/runner/logger.go#L56) and that problem was solved to me. I'm not sure if that change will crash another thing(I tested in OSX and Linux)

**Comment by WhileLoop** [comment]
I am having this issue too. @cosmtrek consider adding a note in big text in the readme that this is a known issue.

**Comment by cosmtrek** [comment]
@cyhhao @thenomemac @WhileLoop Thanks for your patience, I've fixed it, could you try it again?

**Comment by thenomemac** [comment]
Thanks for keeping up with continued contributions. Lots of devs benefit!
