### ISSUE TITLE
Watch directories with names starting with dot (.)

### ISSUE THREAD

**Issue by tmstn** [cosmtrek/air#173]
How can I configure air to watch sub directories whose names start with a dot? It seems to ignore a changes made in these directories completely. I've tried adding the sub directories to the list of included directories but this doesn't help.

**Comment by SuzurikawaChihiro** [comment]
It is only added when isIn and walkDir are true.
Whenever I put something in incloud_dir, isIn becomes false.
Is this a specification?

![image](https://user-images.githubusercontent.com/64934951/120152193-275fc400-c228-11eb-9aeb-be609a30fe9e.png)

**Comment by makiuchi-d** [comment]
As far as reading the source code, there is no way to watch hidden directories that start with ".".
In [/runner/engine.go](/cosmtrek/air/blob/master/runner/engine.go),  it is checked by `isHiddenDirectory()` before adding directory to the watcher.

Please try [arelo](/makiuchi-d/arelo) if you like.
It supports hidden directory watching.

**Comment by tmstn** [comment]
Thanks for your help. I am happy with air for now so I have decided to change the directory structure and not use hidden directories. It would be very useful if air could add a flag to watch hidden directories in the future :+1:
