### ISSUE TITLE
bug: Can't watch in directories that have spaces in path

### ISSUE THREAD

**Issue by mkamadeus** [cosmtrek/air#175]
# What?
I've used air in Windows 10. Works very well, until I tried to run air via WSL. Based on the error message, I deduced that in Linux based systems space are not escaped properly.

# Reproduction
## On Windows (works well)
My path to project: `D:\xxx\something with space\project\main.go`
When running `air`, it works as expected (watches and recompiles)

## On WSL (didn't work)
Used Ubuntu for the WSL distro.

On the same project, on WSL the directory on my machine would be `/mnt/d/xxx/something with space/project/main.go`
When running `air` (via WSL), it does not work and outputs an error message:
```bash
# ...air output
running...
/bin/sh: 1:  /mnt/d/xxx/something: not found
```

**Comment by jacksontong** [comment]
same issue on linux

**Comment by makiuchi-d** [comment]
My PR (#179) also fixes this issue on Linux!

**Comment by wandercn** [comment]
hotbuild.ffactory.org
