### ISSUE TITLE
Re-build is not triggered at times with exclude_unchanged=true

### ISSUE THREAD

**Issue by vishal-wadhwa** [cosmtrek/air#184]
## Description
When an entire file is overwritten, it triggers a WRITE event. The contents 
of the file may however be unchanged.

If there are multiple such files for which WRITE event is fired but content of
only one of those files has changed, in such a case, `air` does not trigger a
re-build if the contents of the file of first event is unchanged.

This happens because after the first event all of the remaining events are 
flushed. This flush may even contain files which have been changed.
But since the file of the first event was unchanged, a re-build is not triggered.

## Reproducing the issue
Added a `README.md` with relevant files and instructions here:
https://gist.github.com/vishal-wadhwa/ef81069f1bcc44bf874004e2c2f11239

## Solution
Fix for this is simple as far as I can understand. We need to evaluate all the events
and flush all events if we have encountered an event which will definitely trigger a
re-build.
PR: https://github.com/cosmtrek/air/pull/185

**Comment by vishal-wadhwa** [comment]
@xiantang  @cosmtrek  Kindly look into this.

**Comment by xiantang** [comment]
ok
