### ISSUE TITLE
difference between bin vs full_bin in config ?

### ISSUE THREAD

**Issue by iangregsondev** [cosmtrek/air#194]
Hi,

I need to pass in some parameters, it seems I can use either bin or full_bin ?

So I am confused, if I use full_bin, then there is no point in using bin ?

```
[build]
  bin = "./tmp/main -c Somethingelse"
  full_bin = "./tmp/main -c LLLLL"
```

Maybe I overlooked something but is it either 1 or the other ?

If that's the case, why do 2 config types exist ? If you can pass arguments to bin then why do I need to use full_bin.

Just interested..

Thanks in advance

**Comment by makiuchi-d** [comment]
According to the commit log, full_bin was introduced for the issue #28.

**Comment by xiantang** [comment]
https://github.com/cosmtrek/air/pull/208 update sample config
