### ISSUE TITLE
is it possible run air on linux/arm64

### ISSUE THREAD

**Issue by macedo** [cosmtrek/air#198]
I'm getting `cosmtrek/air crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/cosmtrek/air/issues/new` when I try to install air on my raspberry.

Is there something that can be done to achieve air running on a linux/arm64?

**Comment by brunocascio** [comment]
Same issue here :D

**Comment by bartek** [comment]
This might be as simple as adding the relevant Platforms to the [case statement within install.sh](https://github.com/cosmtrek/air/blob/master/install.sh#L64). I can confirm that `air` runs fine on my Pi

Notably, my Pi's Platform reports `linux/armv7` so there might be a few cases to cover.

**Comment by shuntagami** [comment]
Maybe fixed by https://github.com/cosmtrek/air/pull/204

**Comment by xiantang** [comment]
> Maybe fixed by #204

merged
