### ISSUE TITLE
Terminal text gets garbled on Windows

### ISSUE THREAD

**Issue by SonarBeserk** [cosmtrek/air#2]
Whenever running air on windows the text has issues printing.

```
λ c:\Users\sonar\.air .

             _
     /\     (_)
    /  \     _   _ __
   / /\ \   | | | '__|
  / ____ \  | | | |
 /_/    \_\ |_| |_|

Live reload for Go apps :)

[19:38:14.574] watching .
[19:38:14.577] watching protos
[19:38:14.579] !exclude tmp
[19:38:14.580] building...
[19:3[81:91:53.83:2155]. 3!2e6x]c l!uedxec ltumdpe
 tmp[
19:38:15.329] !exclude tmp
[19:38:15.341] running...
```
I get this issue running in git bash as well as cmd.

**Comment by cosmtrek** [comment]
Thanks for your report. I'll take time to figure it out. Could you tell me what's your project structure and your Windows version?

**Comment by SonarBeserk** [comment]
I have a single main.go file in the directory that runs an http server. I am running Windows 10 Pro Build 14393

**Comment by cosmtrek** [comment]
@mattn Could you help me look at this issue when you have free time? Actually I have no idea how to solve it because I'm not familiar with Windows terminal, thanks a lot!

@SonarBeserk I'm very sorry for this, it may take long time to fix it. Could you try to fix it if you are able to?

**Comment by mattn** [comment]
Hi, I'll look into it in later.

**Comment by mattn** [comment]
garbage is mixed log-output.

```
[19:3[81:91:53.83:2155]. 3!2e6x]c l!uedxec ltumdpe
```
You must use sync.Mutex to avoid mixed output.

**Comment by cosmtrek** [comment]
@mattn Did you mean this? https://github.com/cosmtrek/air/commit/bf222c248af315e46ab8eba7cab6e66546d6d06f

**Comment by mattn** [comment]
Yes, it fixed this issue on my environment.

**Comment by mattn** [comment]
I found another issue.

![61c9bcb31506e7e3](https://user-images.githubusercontent.com/10111/31873859-e4d329b8-b800-11e7-936d-df451c2db012.png)

I think os.Remove should be called before `go build`.

**Comment by cosmtrek** [comment]
@mattn `os.Remove` just delete the old binary file, actually it's OK to remain this file because the new binary file will overwrite this old one. Could you provide the error?

**Comment by mattn** [comment]
Yes, sequence should be

remove tmp/main.exe
go build (generate tmp/main.exe)

 but as far as I see the output, seems to be:

go build (generate tmp/main.exe)
remove tmp/main.exe

**Comment by mattn** [comment]
Windows can't overwrite file while another process(or it-self) open the file.

**Comment by cosmtrek** [comment]
@mattn Got it, I'll fix this.

**Comment by cosmtrek** [comment]
@mattn I've fixed it, and found another interesting issue about the colorful output. 

See the picture follows:
<img width="1054" alt="screen shot 2017-10-24 at 13 42 30" src="https://user-images.githubusercontent.com/8832222/31926544-ac1eb2ce-b8c1-11e7-9f4f-de465cc2a070.png">

Text in magenta color is invisible in Powershell...

**Comment by cosmtrek** [comment]
@SonarBeserk I've fixed some problems on Windows, could you try a new binary?

```bash
curl -fLo ~/.air.exe \
    https://raw.githubusercontent.com/cosmtrek/air/master/bin/windows/air.exe
```

**Comment by cosmtrek** [comment]
Oops, this issue is closed automatically since current branch `fix-2` was merged by master...

**Comment by SonarBeserk** [comment]
Looks fine, I don't use powershell for go development so that's not something of personal concern. It might be better to open a separate ticket to fix that issue.
