### ISSUE TITLE
CLI arguments bug in windows

### ISSUE THREAD

**Issue by wirekang** [cosmtrek/air#207]
.air.toml
```
[build]
  bin = 'build\\out.exe -dev'
```

main.go
```go
fmt.Println(os.Args[1])  // -dev.exe
```

**Comment by xiantang** [comment]
we need more infomation

**Comment by xiantang** [comment]
could u provide some error log?

**Comment by wirekang** [comment]
The bug is very simple. If you pass any command line arguments by air, the last argument is changed with suffix **.exe**  

Examples: (assume binary file name is out.exe)  
| .air.toml | os.Args |
|---|---|
| bin = "out.exe -arg" | [-arg.exe] |
| bin = "out.exe -arg1 -arg2" | [-arg1 -arg2.exe] |

**Comment by xiantang** [comment]
ok let me check

**Comment by fakery2009** [comment]
Hello, I have the same problem. Is there any solution?

**Comment by xiantang** [comment]
> Hello, I have the same problem. Is there any solution?

I have raised a PR

**Comment by fakery2009** [comment]
> > 你好，我也有同样的问题。有什么解决办法吗？
> 
> 我提出了 PR
ok,thinks

**Comment by fakery2009** [comment]
> > > 你好，我也有同样的问题。有什么解决办法吗？
> > 
> > 
> > 我提出了 PR
