### ISSUE TITLE
 undefined: os.ReadFile

### ISSUE THREAD

**Issue by imperiutx** [cosmtrek/air#245]
Hi air team, I've used air for a while with no problem. But recently, I've received these strange log which make my service can not run like usual in local environment. 

myservice-api     | go: finding golang.org/x/sys latest
myservice-api     | go: finding github.com/mitchellh/go-ps v1.0.0
myservice-api     | # github.com/cosmtrek/air/runner
myservice-api     | ../pkg/mod/github.com/cosmtrek/air@v1.27.9/runner/config.go:211:15: undefined: os.ReadFile
myservice-api     | ../pkg/mod/github.com/cosmtrek/air@v1.27.9/runner/util.go:231:19: undefined: os.ReadFile
myservice-api     | note: module requires Go 1.17
myservice-api     | ...
myservice-api     | ./scripts/web_entrypoint.sh: line 8: air: not found
myservice-api exited with code 127

Below is my web_entrypoint.sh
1 go get -u github.com/cosmtrek/air
2 go get github.com/golang/protobuf/protoc-gen-go@v1.3
3 go get golang.org/x/tools/cmd/godoc
... // some unrelated commands
7 godoc -http=:6060 &
8 air

How can I fix this error?

**Comment by xiantang** [comment]
bcs ur go version is too low to support air. plz, make sure ur go version is higher than 1.17

**Comment by imperiutx** [comment]
I upgraded Go version to 1.17 then my service can run like usual. Thanks @xiantang very much
