### ISSUE TITLE
Release runtime arguments functionality.

### ISSUE THREAD

**Issue by gurleensethi-docker** [cosmtrek/air#263]
Hi 👋 

We have noticed a recent [commit on master](https://github.com/cosmtrek/air/commit/705822078ed1a98bf367ec28eafb3cae46a9c001) has introduced the functionality of runtime arguments, but there is no release tag for it.

Can we please release a new version with the functionality. 😄 

Thank You!

**Comment by raimondsvizulis** [comment]
Seems like this was in plan for v2 as per roadmap, but would be highly appreciated if it's released any time soon.

Thanks!

**Comment by brendensoares** [comment]
why is this delayed for v2? Is it backwards compatible?

**Comment by gcstang** [comment]
Would have been nice but I need this functionality to use the application.

**Comment by xiantang** [comment]
released

**Comment by xiantang** [comment]
plz use v1.30.0
