### ISSUE TITLE
Contribute a Chinese version of documentation

### ISSUE THREAD

**Issue by mophia** [cosmtrek/air#275]
Hello, I'm quite interested in air and I want to submit Chinese version of translation of readme. What can I do ? Can I give a PR on that?

**Comment by xiantang** [comment]
PR is welcome

**Comment by xiantang** [comment]
GOGOGOGO @mophia

**Comment by xiantang** [comment]
any update?

**Comment by mophia** [comment]
I'm sorry about replying you late. I have started to translate the readme, and will submit the PR as soon as possible. Thank you.😀

**Comment by xiantang** [comment]
> I'm sorry about replying you late. I have started to translate the readme, and will submit the PR as soon as possible. Thank you.😀

no problem.

**Comment by xiantang** [comment]
pr is welcome

Vooce ***@***.***>于2022年5月9日 周一18:09写道：
