### ISSUE TITLE
Update and release Go 1.18

### ISSUE THREAD

**Issue by yarabarla** [cosmtrek/air#276]
Hello 😄 !

We have upgraded to the latest version of go (1.18) for generics, etc. and started having problems with air since it's still built using 1.17. The Dockerfile has already been updated to 1.18, but there are still other places like the go.mod that need to be updated, similar to what was [done for 1.17](https://github.com/cosmtrek/air/pull/235/files).

It would be be very helpful if we could get those changes done and released soon.

Thanks!

**Comment by FCollaPi** [comment]
Is there anything that would break if it is mounted using go 1.18 or just updating the go.mod file will make it work?
