### ISSUE TITLE
Add support for override the run command

### ISSUE THREAD

**Issue by brpaz** [cosmtrek/air#28]
Hello. First of all congrats on this project.

I need to setup some environment variables when running my application.
The way I am using without air is having the following command in my project Makefile:

```
server: ## Starts the application server
	APP_ENV=dev go run cmd/server/main.go
````

This works fine standalone but when running the application from air, I need a way to specify the APP_ENV environment variable.

**Comment by cosmtrek** [comment]
I've implemented it, could you try it?

**Comment by cosmtrek** [comment]
I add a new key `full_bin` that meets your needs.

```
[build]
full_bin = "APP_ENV=dev go run cmd/server/main.go"
```
