### ISSUE TITLE
I can't run the cmd about in docker.

### ISSUE THREAD

**Issue by smartdevcode** [cosmtrek/air#281]
`RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin`
The errors are following contents.
 > [dev 1/2] RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin:
#0 1.464 cosmtrek/air info checking GitHub for latest tag
#0 151.4 cosmtrek/air crit unable to find '' - use 'latest' or see https://github.com/cosmtrek/air/releases for details
------
failed to solve: executor failed running [/bin/sh -c curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin]: exit code:

**Comment by xiantang** [comment]
let me take a look

**Comment by anderson-oki** [comment]
@smartdevcode @lalizita Are you try to install via `RUN go get github.com/cosmtrek/air`?

**Comment by xiantang** [comment]
> @smartdevcode @lalizita Are you try to install via `RUN go get github.com/cosmtrek/air`?

why u use install air in this way?

**Comment by lalizita** [comment]
Sorry for the delay,  I loose notifications about it. 
I'm using the docker image like this in my docker-compsoe.yml
```
services:
  web:
    image: cosmtrek/air
```

But I think that it's a problem with M1, in my other computer it works well, but in M1 Macbook doesn't, maybe a problem with fsnotify

**Comment by smartdevcode** [comment]
Perfect.
