### ISSUE TITLE
How about adding "app.go" as the default conf, just like "main.go"

### ISSUE THREAD

**Issue by igordonxiao** [cosmtrek/air#3]
As the title, thanks!

**Comment by cosmtrek** [comment]
In Go world, `main.go` is the default executable file name. 

I think you can copy a `air.conf.example` to your project working directory, and modify build params like

```
...
[build]
bin = "tmp/app"
cmd = "go build -o ./tmp/app app.go"
...
```

Could you explain why you ask for this change?

**Comment by igordonxiao** [comment]
@cosmtrek thank you so much. I am from JS world, most entrance of programs we named it as `app.js`.
