### ISSUE TITLE
Default ExcludeRegex should be empty

### ISSUE THREAD

**Issue by mirefly** [cosmtrek/air#304]
https://github.com/cosmtrek/air/blob/b878e3ce6bf715a9570578f77831c088bdae4732/runner/config.go#L187

Current default value is `[]string{"_test.go"}`. It makes more sense to have empty value as default, and let the user to add `_test.go` in TOML file when needed. With current default value, it seems like that the user cannot add test files back into file watcher with `  exclude_regex = []` in TOML file.

**Comment by xiantang** [comment]
It's look like a bug, we user set exclude_regex = [], but air NOT add test files back into file watcher
