### ISSUE TITLE
Error under wsl when `'` is included in the name

### ISSUE THREAD

**Issue by fedevilensky** [cosmtrek/air#305]
Pretty much as the title says. I was running under wsl, inside a directory containing a `'` in the name

When trying to launch the program, the path is not escaped correctly, and the `'` breaks the command

![image](https://user-images.githubusercontent.com/19208605/177806114-b5d5dd12-9f45-4e59-8d88-42e5e2aaa9ed.png)

I don't know if a fix is trully necesary. I just wanted this problem to be documented somewhere, so if anyone else comes across this problem, they know what's happening and that it's easily solved by changing the directory's name

**Comment by xiantang** [comment]
OK

**Comment by xiantang** [comment]
I dont think it need to fix, just need  add `\` before `'`

**Comment by xiantang** [comment]
updated in Readme
