### ISSUE TITLE
`include_file` option for single files

### ISSUE THREAD

**Issue by silverwind** [cosmtrek/air#307]
I like to exactly specify files and directories to be watched so `air` initializes quickly and does not iterate useless directories. This mostly fine using the `include_dir` option with a list of to-watch directories, but it's not possible watch files in the root directory without adding the root directory itself.

How about having a `include_file` option, where one can put single files to watch? E.g.

```toml
[build]
include_dir = ["modules", "libs"]
include_file = ["main.go"]

**Comment by silverwind** [comment]
https://github.com/cosmtrek/air/pull/337

**Comment by xiantang** [comment]
looks good
