### ISSUE TITLE
failed to watching too many open files, error: %!s(MISSING)

### ISSUE THREAD

**Issue by williambao** [cosmtrek/air#32]
It's seems cannot run correctly when i have too many golang files...

<img width="797" alt="Screen Shot 2019-12-03 at 12 10 15" src="https://user-images.githubusercontent.com/779521/70019919-fc11ff80-15c5-11ea-80e4-630fe5bbb7ac.png">

**Comment by cosmtrek** [comment]
Please refer to https://github.com/fsnotify/fsnotify/issues/129.
