### ISSUE TITLE
failed to watching, error: bad file descriptor

### ISSUE THREAD

**Issue by lz-freedom** [cosmtrek/air#328]
<img width="754" alt="iShot_2022-09-13_11 54 48" src="https://user-images.githubusercontent.com/32818030/189804002-2ce9d696-d41a-4e6d-bd3a-c1ff4c37e7a1.png">
<img width="932" alt="iShot_2022-09-13_11 54 19" src="https://user-images.githubusercontent.com/32818030/189804010-43c9bed2-700e-4392-9c31-ad362c3f98ae.png">

**Comment by daifangyun** [comment]
ulimit -n 2048
