### ISSUE TITLE
Does docker-compose support configuring multiple directories(working_dir)?

### ISSUE THREAD

**Issue by yun36524** [cosmtrek/air#339]
![image](https://user-images.githubusercontent.com/104484993/196880584-75b1ea0b-b647-4bd2-b5e2-b8945befc805.png)
I need to start multiple services at the same time, listening to their respective directories,how should i configure.
Also maby a dummy question since I'm a noob. Docker compose how to auto configure go env when it starts running,like proxy.

**Comment by xiantang** [comment]
docker-compose does not support configuring multiple directories.
don't put multiple services in the same container, one service one container.

u can read this https://docs.docker.com/language/golang/develop/#configure-docker-compose
