### ISSUE TITLE
Some files extensions do not reload

### ISSUE THREAD

**Issue by mwehbe** [cosmtrek/air#340]
First thanks a lot for this very good golang hot reload tool.

One issue i have:
My golang templates files have .gohtml extension, and they are not reloaded when modified although set in .air.toml

include_ext = ["go", "**gohtml**", "css", "env", "tpl", "tmpl", "html", "json"]

Best regards

**Comment by xiantang** [comment]
reproducing

**Comment by xiantang** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/34479567/197460234-f0469e49-92c2-462c-90aa-cb8859020e65.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/34479567/197460246-15c54c5d-2435-478b-9e8b-24364c0d5fd3.png">

cannot repreduce, I will close this issue first, if u have reproduce step, u can reopen issue
