### ISSUE TITLE
support for yaml configuration file?

### ISSUE THREAD

**Issue by dirsigler** [cosmtrek/air#341]
It sounds quite trivial, but I would be interested if there is support to also write the air configuration file in yaml.

If not, I would love to see support for a yaml configuration file.
All of my configuration files in a project are already either JSON or YAML files which means I also have the linting and extensions already in place for these. TOML is quite rare.

**Comment by xiantang** [comment]
u can support YAML file, PR is welcome

**Comment by xiantang** [comment]
if u want, u can also support JSON. haha

**Comment by xiantang** [comment]
I will close this Merge request, if PR  is ready, plz tag me

**Comment by christopher-kleine** [comment]
@xiantang Could you review PR #455 ? It shouldn't break anything and is backwards compatible.
Let me know if there's something missing.

**Comment by christopher-kleine** [comment]
> u can support YAML file, PR is welcome

Is this still valid? My PR for exactly is open for a few weeks now.
Not even a quick response.
And I'm not the only one who is waiting for a response.

Is this project still maintained? Except for like 2 PRs, the whole interaction seems a bit lacking.

**Comment by christopher-kleine** [comment]
As mentioned, I closed my PR and start managing my own fork now.
