### ISSUE TITLE
gin.SetMode 卡死

### ISSUE THREAD

**Issue by whlvv** [cosmtrek/air#345]
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	gin.SetMode(gin.ReleaseMode)
	r := gin.Default()

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run() // 监听并在 0.0.0.0:8080 上启动服务
}

**Comment by xiantang** [comment]
<img width="1512" alt="image" src="https://github.com/cosmtrek/air/assets/34479567/617316b4-5d01-4a12-845f-efa6b7d56d02">
cannot reproduce
