### ISSUE TITLE
failed to watch /app, error: permission denied

### ISSUE THREAD

**Issue by leandergangso** [cosmtrek/air#349]
![image](https://user-images.githubusercontent.com/60340480/199609314-26d62969-2f8b-4eb9-bea6-b436fe7a71a2.png)

I'm using the provided docker image with docker-compose and setting both working_dir and volume to /app.
If volume and working_dir is different then the error is gone, but then wont detect changes.

**Comment by quocnguyen** [comment]
one or some folders in your /app generated by somethings else that air do not have permission to watch.

**Comment by ryoshindo** [comment]
I had the same error, but in my case it was because the package name of the file with `main()` was not `main`.
Thus, the error disappeared by modifying the file as follows

```diff
- package app
+ package main
```

**Comment by renatospaka** [comment]
I have a fresh instalation (v1.49.0, built with Go go1.20.6) and I get "Permission denied" on every execution attempt.
My setup is a WSL (ubuntu) running over W11. All executions run with my personal user in Linux, so air should have access to everything

![air_error](https://github.com/cosmtrek/air/assets/33945081/c74c74ea-b789-4936-9357-a7cab22846af)

Anyway, if I change something in my code, I can see that air notices it and reprocesses all stuff properly.

What could be wrong?

**Comment by leandergangso** [comment]
@renatospaka just a suggestion, but might work if you put the cmd/server.go file at the root of your project instead of inside cmd/.

**Comment by renatospaka** [comment]
This is how `toml` file is configured:
```
  bin = "./cmd/server/server"
  cmd = "GOOS=linux CGO_ENABLED=0 GOARCH=amd64 GO111MODULE=on go build -ldflags='-w -s' -o cmd/server/server cmd/server/main.go"
```
I have figured out what was wrong: both folder and binary have the same name (server). As soon as I fixed it in the `toml` file, it worked.  Well, not exactly sure, now I have another error, but this one is related to a missing parameter.
