### ISSUE TITLE
Manually trigger reload

### ISSUE THREAD

**Issue by sazzer** [cosmtrek/air#351]
It would be very useful if there was some way to trigger a reload manually without needing to change one of the watched file. For example, in nodemon you can enter `rs<Enter>` into the terminal and it will trigger a reload, but as best I can tell there's no way to do this with Air.

It's not a huge problem - you can always just save an unchanged file, or stop and restart Air - but it would be convenient.

Cheers

**Comment by amikai** [comment]
Hi @sazzer, air now support rerun, see the [example](https://github.com/cosmtrek/air/blob/master/air_example.toml#L41-L44).
