### ISSUE TITLE
Air not running with --tags dynamic (Apple M1)

### ISSUE THREAD

**Issue by themiken** [cosmtrek/air#352]
I'm trying to start a project with Kafka library that in my Apple M1 doesnt run correctly. In a confluent issue https://github.com/confluentinc/confluent-kafka-go/issues/591 suggests run _go build --tags dynamic_ but when i run this code with air _air  --build.cmd "go build --tags dynamic_  throws me following error

<img width="737" alt="Screen Shot 2022-11-14 at 7 16 59 PM" src="https://user-images.githubusercontent.com/8595578/201796559-547b7fa7-ecef-4cc6-9055-d9d5a4f91645.png">
<img width="814" alt="Screen Shot 2022-11-14 at 7 17 22 PM" src="https://user-images.githubusercontent.com/8595578/201796683-d06c3183-2d9c-497e-bbb8-256b476ec287.png">

**Comment by xiantang** [comment]
if u just use command line to run `go build --tags dynamic`, is this correct?

**Comment by themiken** [comment]
if i just run `go build --tags dynamic` and then run the binary works fine.

<img width="606" alt="Screen Shot 2022-11-15 at 8 46 25 AM" src="https://user-images.githubusercontent.com/8595578/201936138-4418b453-571a-4bf2-89aa-b7cfa0f501a0.png">
<img width="749" alt="Screen Shot 2022-11-15 at 8 46 49 AM" src="https://user-images.githubusercontent.com/8595578/201936155-19c99da8-1582-416f-9bc2-283eaf9bb639.png">

Thank you for supporting!!!

**Comment by xiantang** [comment]
can u run this: 
10:20 ➜  ~ /bin/sh
sh-3.2$ go version
and compare version with commandline

**Comment by themiken** [comment]
Resuming this post.

I solved the problem running this command

`air --build.cmd "go build --tags dynamic -o bin/api main.go" --build.bin "./bin/api`

Previously I follow this post (for this project I use confluent-kaka)

https://github.com/confluentinc/confluent-kafka-go/issues/591

go version go1.18 darwin/arm64
