### ISSUE TITLE
Air should support executing binary again when executable exit

### ISSUE THREAD

**Issue by tymonx** [cosmtrek/air#353]
Currently it doesn't execute binary again when exit. It does only when file changes. `Air` should exit with the same status code as exited binary **OR** rerun binary again with optional configurable delay. Both features should be configurable and may be disabled on default to keep backward compatibility.

**Use case:**
Microservices or long-running applications can be run as services under Docker Compose with the `restart: always` option, Docker Swarm or other container orchestration solution. For development purpose `Air` can be also run in these environments. But some applications/frameworks terminate running application for example because of unreachable message broker or database service instance. And orchestration rerun them again. But with `Air` it never happens. Because `Air` never exit or rerun binary when binary exit by itself.

**Comment by xiantang** [comment]
good feature.
So air needs to check whether the process is alive, if not alive air should restart the process.
I will do this.
