### ISSUE TITLE
Less verbose logging

### ISSUE THREAD

**Issue by perholmes** [cosmtrek/air#354]
Hi,

Air has some extremely heavy logging on startup, and in a cluster with ten Go containers all starting up Air at the same time, we're talking 4-5 screens of boilerplate logging, making it very hard to catch actual problems during startup.

Is there a silent mode? Or a quieter mode? I don't mind Air saying it has started and when a file changes. But the remaining 100x logging is unnecessary and potentially harmful, because log spam will hide actual problems that a human should notice.

**Comment by silverwind** [comment]
https://github.com/cosmtrek/air/issues/201 is related.
