### ISSUE TITLE
cosmtrek/air crit platform linux/armv7 is not supported.

### ISSUE THREAD

**Issue by alltried** [cosmtrek/air#357]
Can cosmtrek/air adding armv6/armv7 support?

**Comment by silverwind** [comment]
Try with `go install` which will compile:

```
go install github.com/cosmtrek/air@latest
```

**Comment by alltried** [comment]
> already tried, after run the command, 'air -v' still not echo nothing

**Comment by silverwind** [comment]
Try compile and run, this needs go 1.17+:

```
go run github.com/cosmtrek/air@latest
```
