### ISSUE TITLE
Can't install air via cURL:  cosmtrek/air crit unable to find '' - use 'latest'

### ISSUE THREAD

**Issue by joweich** [cosmtrek/air#368]
### Goal
Installing air with one of the cURL commands described in the _README_:
`curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin`
`curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s`

### Issue
Installation fails while logging (both with and without sudo):

> cosmtrek/air info checking GitHub for latest tag
> cosmtrek/air crit unable to find '' - use 'latest' or see https://github.com/cosmtrek/air/releases for details

### Environment

- curl 7.86.0
- go 1.19.4 linux/amd64
- Ubuntu 22.04.1 LTS

**Comment by xuanlongvts** [comment]
the same
