### ISSUE TITLE
build from multiple go files

### ISSUE THREAD

**Issue by 2x2xplz** [cosmtrek/air#37]
Using Windows 10 Pro

I have code in two files: `main.go` and `handlers.go`.

When I build from the command line, no problem: `go build -o ./tmp/main.exe`. But when I use that same command within `.air.conf`, it seems it only builds `main.go` and ignores `handlers.go`, because I get the error message:

```
.\main.go:14:19: undefined: firstFunc
.\main.go:15:22: undefined: secondFunc
```

the exact line in the config file is `cmd = "go build -o ./tmp/main.exe"`

**How can I run a build within air that includes all the \*.go files?**

Note -- this also fails: `cmd = "go build -o ./tmp/main.exe main.go handlers.go"`  However even if this worked, it seems like an unsatisfactory answer, eventually I may have a list of 10, 20, 50 files.

**Comment by cosmtrek** [comment]
It does support multiple go files. I think something wrong in your config.

**Comment by olup** [comment]
Got this problem too. Building takes only main into account. Using default conf here.

**Comment by 2x2xplz** [comment]
> It does support multiple go files. I think something wrong in your config.

I have a very simple setup. Perhaps you can provide an example in the README that covers multiple files? Thank you.

**Comment by cosmtrek** [comment]
May like this:
```
cmd = "go build -o ./tmp/main ."
```

**Comment by antonderegt** [comment]
How could I use multiple files when using Docker? Normally I update the Dockerfile, but that isn't possible when using air.

**Comment by antonderegt** [comment]
> Got this problem too. Building takes only main into account. Using default conf here. Using ubuntu 19 and latest go.

Same here, I use the default config and get the same error: 
```
./main.go:17:5: undefined: db
```

**Comment by cosmtrek** [comment]
@antonderegt What's your project structure and go version?

**Comment by olup** [comment]
https://github.com/cosmtrek/air/issues/37#issuecomment-570935350 solved it for me indeed. Thanks ! Maybe should be the default ?

**Comment by antonderegt** [comment]
My Go version is which every you use in the Docker image, I don't have Go installed on my machine.

Folder structure:
.
├--- db
 &nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;  └─db.go
├--- main.go
├--- .air.conf
├--- go.mod
├--- go.sum
  

This is the simple example I'm trying to get working:
```
package main

import (
    "fmt"
    "net/http"
    "db"
)

func main() {
    http.HandleFunc("/", HelloServer)
    http.ListenAndServe(":8080", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello you, %s!", r.URL.Path[1:])
    db.Test()
}
```

Error message: 
```
build github.com/cosmtrek/air: cannot load db: malformed module path "db": missing dot in first path element
failed to build, error: exit status 1
```

I run the container with the command from the README:
```
docker run -it --rm \
    -w "/go/src/app" \
    -v $(pwd):/go/src/app \
    -p 8080:8080 \
    cosmtrek/air
```

I hope this information is useful to you.

**Comment by antonderegt** [comment]
It looks like I fixed the issue by doing the following:

In go.mod (same dir as main.go) I added these lines:
```
require github.com/antonderegt/db v0.0.0
replace github.com/antonderegt/db v0.0.0 => ./db
```

In the db folder I added an empty go.mod
After that I was able to import the local package this way:

```
"github.com/antonderegt/db"
```

I'm new to Go, if this is the standard Go way, I'm sorry for wasting your time ;)
