### ISSUE TITLE
Is it possible to debug my docker Go app in vscode?

### ISSUE THREAD

**Issue by laurencefass** [cosmtrek/air#378]
I'm running cosmtrek/air in a docker container and I am trying to debug it using vscode remote extensions by attaching to the running container. The debugger works if i attach to the target process I want to hot reload but all my breakpoints are disabled saying cant find the files. 

Have you/anyone ever successfully debugged a go app running in cosmtrek/air  with working breakpoints?

Part of my issue is I dont really know what the correct settings should be for launch.json and settings.json.

Any help of advice appreciated

**Comment by subhroacharjee** [comment]
any solutions?

**Comment by rushairer** [comment]
mark

**Comment by wowuliao11** [comment]
I have same question!
