### ISSUE TITLE
Request feature for pause in build fail

### ISSUE THREAD

**Issue by sharefantasy** [cosmtrek/air#38]
Hi, I would like to request for a feature. My development scene is this.
* Run "make build" as building command
* Output artifacts are not cleared before new build

So after build failed, Air runs the the previous success built artifact without noticing. I think a pause would be enough.

Could you please support this feature? thanks :)

Btw, I use air as nginx configuration reloader as well, it's awesome.

**Comment by tobias-kuendig** [comment]
This is a must have feature. Too many times the error message gets burried in my own process' output. The reloading has to stop once a build failed and then start over once it's fixed!

**Comment by cosmtrek** [comment]
No problem, an option will be added to meet your requirement :)

**Comment by cosmtrek** [comment]
@sharefantasy @tobias-kuendig Done, could you try the latest version?

**Comment by tobias-kuendig** [comment]
Had to add `stop_on_error = true` to the config and now the build stops on error. Works like a charm, thank you @cosmtrek!

**Comment by sharefantasy** [comment]
Thanks! works well in my environment! :)
