### ISSUE TITLE
install.sh appears to be broken

### ISSUE THREAD

**Issue by ocasta181** [cosmtrek/air#384]
```
=> [ 6/12] RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh                                                                            0.4s
 => [ 7/12] RUN chmod +x install.sh                                                                                                                                              0.2s
 => ERROR [ 8/12] RUN sh install.sh                                                                                                                                              1.6s 
------                                                                                                                                                                                
 > [ 8/12] RUN sh install.sh:                                                                                                                                                         
#0 0.207 cosmtrek/air info checking GitHub for latest tag
#0 1.232 cosmtrek/air info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/linux/arm64
------
failed to solve: executor failed running [/bin/sh -c sh install.sh]: exit code: 1
```

**Comment by K-shir0** [comment]
I had this problem too, but it seems to be fixed now.

**Comment by dieguezz** [comment]
Happens to me as well, i am using arch linux. 

I tried installing with `curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s ` but there was no file in `~/.bin` nor any other place like */bin/air after searching with `mlocate`

Finally i installed it with `go install ...`

**Comment by cosmtrek** [comment]
@ocasta181 I've tested that command, and it can install air. Maybe you need to check your network. 😃

**Comment by dieguezz** [comment]
> @ocasta181 I've tested that command, and it can install air. Maybe you need to check your network. smiley

So i have no network to use curl but i have network to use go install? That does not make sense to me. Also, there was no error when running curl. 

![image](https://user-images.githubusercontent.com/1161455/224952391-fff65b33-faa4-4974-b4ba-be82e5f995c9.png)

I think that the problem might be that it is trying to install it in `./bin` and not in `/bin` so then it depends where you install it from
