### ISSUE TITLE
Exclude specific files

### ISSUE THREAD

**Issue by ihgann** [cosmtrek/air#39]
AFAICT, there is currently no way to ignore specific files. This is especially pervasive for 2 reasons:

1) Generated files
2) Intermediate files

If either happens to have a specific extension you want watched (and most likely it will be `.go`), then unless it's always guaranteed to be in a specific directory these will always be watched.

I think instead of just `exclude_dir`, it should be possible to exclude specific files as well.

**Comment by ihgann** [comment]
I see #22 seems to be attempting to address this. Any chance that is going to be approved?

**Comment by cosmtrek** [comment]
@ihgann  It does make sense, I’ll implement it ASAP :P

**Comment by cosmtrek** [comment]
@ihgann Done, could you try the latest version?

**Comment by ihgann** [comment]
@cosmtrek It works great! Also, *really happy* to see the new logging fixes to not truncate application logs. This update is awesome! :)
