### ISSUE TITLE
Is it possible to put the config file in a subdirectory?

### ISSUE THREAD

**Issue by onattech** [cosmtrek/air#390]
Hi,
I am not very hopeful but wanted to ask just in case. Is it possible to put the config file in a subdirectory? My motivation is to keep the root directory as lean as possible.
![image](https://user-images.githubusercontent.com/53895969/216779945-57390e1f-c3cc-4b17-a852-39d2b377d9de.png)

**Comment by makiuchi-d** [comment]
`air -c config/.air.toml`

**Comment by onattech** [comment]
Thank you! That worked.
