### ISSUE TITLE
reloading runs twice everytime.

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [cosmtrek/air#391]
![err](https://user-images.githubusercontent.com/67856304/217291077-943af717-1d63-4b13-8c6a-8ac4253ff808.PNG)

- all versions are latest(golang, extension + vscode)
- when i run air(with toml) reload triggered twice for every changes.

**Comment by imfaser** [comment]
I also encounter this preblem. you can set delay to 1000 in ‘.air.toml’. if you do that ,the issue will be solved
