### ISSUE TITLE
"Buy Me a Coffee" url is 404

### ISSUE THREAD

**Issue by justinclift** [cosmtrek/air#398]
Looking down the README file, it has a url near the end to "Buy Me a Coffee":

  https://www.buymeacoffee.com/36lcNbW

Visiting that url though gives a 404 error:

![image](https://user-images.githubusercontent.com/406299/224853095-5e66ff36-b558-42b0-ab9c-4dfaf5ab632e.png)

**Comment by cosmtrek** [comment]
Thanks, I'll fix it 😄
