### ISSUE TITLE
Docker air:/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by air)

### ISSUE THREAD

**Issue by anderson-comvex** [cosmtrek/air#415]
## Description

Air Version: `v1.43`

On AMD64 CPU Architectures of Mac Intel, the image is built successfully but when trying to run the container we get `air: /lib/x86_64-linux-gnu/libc.so.6: version` GLIBC_2.32' not found (required by air)`.

Tried both [Go](https://hub.docker.com/_/golang/) 1.19 and 1.20.

Air is being installed using: 

```sh
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
```

## Additional Details

It looks like the gclib of the images are 2.31 tho when running: `find /lib -iname 'libc*.so'`

```
/lib/x86_64-linux-gnu/libc-2.31.so
```

But for ARM64 on Mac Silicon, seems to be running fine with the libc-2.31

## Workaround

Lock the version to `v1.42` or before.

**Comment by arckadious** [comment]
Same issue here, I tried to downgrade air version, but still the same:  GLIBC_2.32' not found (required by air). Any ideas ?

**Comment by silverwind** [comment]
Try the [go install](https://github.com/cosmtrek/air#via-go-install) method.

**Comment by feline-fanatic** [comment]
@anderson-comvex I am getting the same issue with `v1.42`. What base image are you using in your dockerfile?

**Comment by arckadious** [comment]
I had the same issue.

Use debian:bookworm image, instead of debian:latest image. This image is
not yet "stable" but Glibc 2.32 will be available.



Le jeu. 27 avr. 2023 à 19:08, Lindsey Todd ***@***.***> a
écrit :

**Comment by arckadious** [comment]
I had the same issue.

Use debian:bookworm image, instead of debian:latest image. This image is
not yet "stable" but Glibc 2.32 will be available

Le jeu. 27 avr. 2023 à 19:08, Lindsey Todd ***@***.***> a
écrit :

**Comment by anderson-comvex** [comment]
> @anderson-comvex I am getting the same issue with `v1.42`. What base image are you using in your dockerfile?

I added the Docker image from Dockerhub we are using as base image on the Issue Description.

**Comment by silverwind** [comment]
The fix is likely to build the app with `CGO_ENABLED=0`, assuming no CGO dependencies.

**Comment by veritymedia** [comment]
Had same issues even now. go install worked, curl gave the error

**Comment by xiantang** [comment]
https://github.com/cosmtrek/air/pull/450 I think this PR should fixed
