### ISSUE TITLE
address already in use 

### ISSUE THREAD

**Issue by herrluk** [cosmtrek/air#421]
System Version: macOS 13.3.1 (22E261)
      Kernel Version: Darwin 22.4.0

When I used air, except for the first time, hot loads always had port occupancy issues
<img width="845" alt="image" src="https://user-images.githubusercontent.com/35862764/235859537-c45b3114-68e4-47ca-ac33-f4bc4237ed90.png">
This is the port usage using Chrome
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/35862764/235859134-4f805e94-d228-4b88-994f-ef4df7f43b8d.png">

**Comment by endigma** [comment]
happening to me too, intermittent

**Comment by hielfx** [comment]
Hi! Please check https://github.com/cosmtrek/air/issues/216#issuecomment-983550776 and see if those settings solve the problem for you.

Hope it helps!

**Comment by azmiadhani** [comment]
I use macOS, downgrading air from v1.43.0 to v1.27.0 works for me

**Comment by yg7001** [comment]
> Hi! Please check [#216 (comment)](https://github.com/cosmtrek/air/issues/216#issuecomment-983550776) and see if those settings solve the problem for you.
> 
> Hope it helps!

`delay=1000` and `kill_delay="10s"` resolve this problem for me (go 1.20.4 on windows)

**Comment by vincentvella** [comment]
Is there a reason https://github.com/cosmtrek/air/issues/216#issuecomment-1543737187 isn't the default?
