### ISSUE TITLE
input air，can‘t run code

### ISSUE THREAD

**Issue by Nadir-Echo** [cosmtrek/air#423]
I input the "air",and I want to run the code but failed.
![image](https://user-images.githubusercontent.com/86950349/236673226-0bbcc1ff-bf7e-498a-af9d-635422d80f94.png)

I have already downloaded the air package,and in the dictionary, have the .air.toml file.
![image](https://user-images.githubusercontent.com/86950349/236673182-c01e8f9a-3f46-4c80-92a6-0ed62a44c609.png)

**Comment by Nadir-Echo** [comment]
配置环境变量以后可以使用air命令，但是运行会报错
![image](https://user-images.githubusercontent.com/86950349/236675409-440e2c5a-56fc-4aa3-bfbd-de4047caad6f.png)

**Comment by killlowkey** [comment]
> 配置环境变量以后可以使用air命令，但是运行会报错 ![image](https://user-images.githubusercontent.com/86950349/236675409-440e2c5a-56fc-4aa3-bfbd-de4047caad6f.png)

Because of platform compatibility issues, download the source code and compile it yourself to solve.

**Comment by xiantang** [comment]
p
