### ISSUE TITLE
Duplicate process after reload

### ISSUE THREAD

**Issue by ViceEye** [cosmtrek/air#426]
![image](https://github.com/cosmtrek/air/assets/17517159/0a3f64fb-4ad5-48a3-baa7-3b34845af230)

![image](https://github.com/cosmtrek/air/assets/17517159/97839172-c561-4998-afa5-af879f2a8335)
Code changes under ./cmd are not detected and not reloading

and cd to `./cmd` and run `air` with config under `./cmd`  then it will work, tried change `root = "."` to `root = "./cmd"` but still not detecting changes

![image](https://github.com/cosmtrek/air/assets/17517159/1a94fa1d-e910-4cb2-8c17-ad68ff887db5)

**Comment by Solander** [comment]
I have the exact same problem. I'm now up to 5 processes that will reload and 4 of them give error due to my api port is already in use.

Have anyone else had this and solved it?

**Comment by JsThiago** [comment]
Same here. ChatGPT told me to implement graceful shutdown but didn't worked.

**Comment by badjem79** [comment]
same here...
![image](https://github.com/cosmtrek/air/assets/5801803/de5b2f40-e93c-40f4-83c3-b4323c3e6b97)
I was tinking that visual studio code is saving file multiple times but, also with notepad is the same...
I think that air should verify if a build is on-going and not start more builds at the same time...

**Comment by pablor21** [comment]
Try to change the .air.toml with the following values:

kill_delay = "10s"
delay = 500

It should work.

**Comment by suntong** [comment]
> It should work.

Unfortunately, not quite, it might work first, but will fail eventually:

```
  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ , built with Go 1.21.0

watching .
!exclude tmp
building...
running...
2023/09/07 16:48:36 Listening on :8080...
main.go has changed
building...
main.go has changed
running...
2023/09/07 16:48:55 Listening on :8080...
main.go has changed
building...
main.go has changed
building...
running...
running...
2023/09/07 16:49:44 Listening on :8080...
2023/09/07 16:49:44 Listening on :8080...
2023/09/07 16:49:44 ListenAndServe: listen tcp :8080: bind: address already in use
```

IE, at `16:48:36` air detect changes twice, and survived, but after `16:48:55` air detected changes again, but this time **multiple** buildRuns will run simultaneously.

I think the root cause is to fix why there are **multiple** instances running simultaneously.

**Comment by MaximilianGaedig** [comment]
Just got into go and air, and this happened to me aswell, logs (http example):
```go

  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ , built with Go

watching .
!exclude tmp
building...
running...
main.go has changed
building...
main.go has changed
running...
main.go has changed
main.go has changed
building...
building...
running...
running...
2023/09/20 18:07:30 listen tcp :8080: bind: address already in use
main.go has changed
building...
main.go has changed
building...
running...
running...
2023/09/20 18:07:36 listen tcp :8080: bind: address already in use
```
