### ISSUE TITLE
Not receiving the logs when i run the code.

### ISSUE THREAD

**Issue by Valy2255** [cosmtrek/air#430]
I don t receive the logs when i run my proggram with air , only when i run the main.go. I don t have any problem with watched  folders and sub-folders. Also , on mac it works , but on windows not. Does anynbody know what can be the problem ?

![2023-06-02 (2)](https://github.com/cosmtrek/air/assets/119352194/229d191b-1eb3-41ca-a705-9cf9ba5fc7fc)

**Comment by eitamal** [comment]
I've been having the same issue on Windows, only I get the logs eventually when I Ctrl+C out of air, which kind of defeats the purpose of air in some sense.

**Comment by BrendanMartin** [comment]
same here

**Comment by swengineer404** [comment]
Still no fix????

**Comment by makiuchi-d** [comment]
It is the same as #412.
There is a PR (#389) fixes this but has not been reviewed yet.

**Comment by xiantang** [comment]
I don't have windows device qaq
