### ISSUE TITLE
Why does it need a custom install.sh?

### ISSUE THREAD

**Issue by coxley** [cosmtrek/air#434]
This works just fine, and is common for Go commands:

```
go run github.com/cosmtrek/air@latest --help

# or

go install github.com/cosmtrek/air@latest
```

Recommending people `curl | sh` always feels sketchy. After taking a quick look, I didn't see anything in it that was necessary. I can only assume that `go install` works the same across each platform it supports. Maybe you've found that isn't the case, and can ignore me. :)

**Comment by xiantang** [comment]
when we use go install github.com/cosmtrek/air@latest, we can't put version by air -v

**Comment by xiantang** [comment]
info, ok := debug.ReadBuildInfo()
I suppose that I can use logic like this : https://github.com/mvdan/gofumpt/blob/master/internal/version/version.go#L37
