### ISSUE TITLE
`kill_delay` is in nanoseconds and not milliseconds as the example toml shows

### ISSUE THREAD

**Issue by varunbpatil** [cosmtrek/air#436]
The example toml configuration file shows `kill_delay` as being in milliseconds

https://github.com/cosmtrek/air/blob/32675c4c222db3c187c2073340ccb3ff26ace1e2/air_example.toml#LL44C4-L44C4

but it is actually in nanoseconds which makes it unlike all the other time related configs which are in milliseconds.

**Comment by varunbpatil** [comment]
Unfortunately, fixing this, although easy, is a backward incompatible change. So, I'm fine with simply updating the example toml configuration file.

**Comment by xiantang** [comment]
I think modifying the toml configuration file will suffice. Can you submit a PR?
