### ISSUE TITLE
Support Pre & Post build scripts

### ISSUE THREAD

**Issue by kareemmahlees** [cosmtrek/air#453]
## Context
I was creating a fiber API and wanted to run the `swag fmt` and `swag init` commands before each build.

## Wanted Solution
```config
[build]
    pre_cmd = [ "swag fmt", "swag init" ] 
    cmd = "go build -o ./tmp/main.exe ."
    post_cmd = [ " some other scripts " ]
```

If the maintainers are ok with this you can assign this to me and I will happily work on it :smile:

**Comment by xiantang** [comment]
If you have submitted a PR and have sufficient unit tests, I am happy to merge it

**Comment by armada45-pixel** [comment]
Oh thank @kareemmahlees ! I'm finding this features.
