### ISSUE TITLE
Multiple buildRuns still run simultaneously

### ISSUE THREAD

**Issue by suntong** [cosmtrek/air#473]
I know the root cause now, it's because when you save your code in a short period of time, air will start duplicate processes, but doesn't have any lock for it.

_Originally posted by @xiantang in https://github.com/cosmtrek/air/issues/457#issuecomment-1754768521_

**Comment by suntong** [comment]
Thanks for fixing #216, now the _"port address already in use"_ issue has been fixed. 

Yet, the air will _**still**_ start duplicate **build** processes, like I originally reported in https://github.com/cosmtrek/air/issues/216#issuecomment-1751531229

- It dramatically slow down the build process on my tiny VPS, and
- it results in duplicated error messages. The worst case I got was over 10 duplicated error message copies, taking a huge chuck of my scrollback spaces.

Please doublecheck.

**Comment by suntong** [comment]
Eventually the processes grow so out of the control, 

![image](https://github.com/cosmtrek/air/assets/422244/ad34f9f7-2e20-44f7-98a1-4370ede62f42)

that even `^C` to stop it will take several minutes :( :(

**Comment by xiantang** [comment]
https://github.com/cosmtrek/air/commit/4603314db840710d1762e1e4a1527cfc9c7d90c0 should be fix by
