### ISSUE TITLE
Does not support arguments

### ISSUE THREAD

**Issue by andrew-morris** [cosmtrek/air#52]
My code requires that we follow the execution with a "serve" argument. Is this supported?

I noticed this PR but it seems to be closed:

https://github.com/cosmtrek/air/pull/12

**Comment by JamesMura** [comment]
I think you can add your arguments to the full_bin configuration item [here](https://github.com/cosmtrek/air/blob/0b8fa64fe007c34001bc2ad7279bb94e71588f5f/air_example.conf#L14)

**Comment by andrew-morris** [comment]
You're exactly right. Thanks!
