### ISSUE TITLE
Windows path compatibility issue

### ISSUE THREAD

**Issue by Zhwt** [cosmtrek/air#53]
First of all, thanks for the great work!

I'm using Windows 10 Enterprise Edition 1607 LTSB, and my .air.conf file is like:

```ini
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ."
bin = "tmp/main.exe"
full_bin = "tmp\main.exe"
```

It seems air is using `cmd` to spawn go processes, by default it will generate `tmp is not recognized as an internal or external command` error, so I changed the `\` in `full_bin` property to `/`, others are the same as [air_example.conf](https://github.com/cosmtrek/air/blob/master/air_example.conf).

Then every time after I changed something, air reloads the peoject, and the console will output an error:

```
failed to remove C:\path\to\project\tmp\main.exe, error: remove C:\path\to\project\C:\path\
to\project\tmp\main.exe: The filename, directory name, or volume label syntax is incorrect.
```

It is removing `C:\path\to\project\C:\path\to\project\tmp\main.exe` while the correct file path is `C:\path\to\project\tmp\main.exe`. My condition is a little different from [issue#2](https://github.com/cosmtrek/air/issues/2#issuecomment-338559319), I don't know why but my windows can remove a file that is in use. And besides the error message, everything just works fine, the program actually gets reloaded and serving correct contents.

**Comment by Zhwt** [comment]
The problem is probably related to 

https://github.com/cosmtrek/air/blob/f5010ecb13e740523cbe8dbe175d3f07febad8af/runner/config.go#L192-L194

Both `c.Root` and `c.Build.Bin` are absolute paths.

**Comment by cosmtrek** [comment]
Sorry, I work on macOS and Debian all the time, not well known at Windows. I would greatly appreciate your contributions.

**Comment by xiantang** [comment]
https://github.com/cosmtrek/air/pull/122 close
