### ISSUE TITLE
Air not being installed in zsh path on macOS

### ISSUE THREAD

**Issue by omicron1100** [cosmtrek/air#558]
Followed instructions to install Air via `go install` using zsh on macOS but it gives the error `zsh: command is not found: air`. Tried to follow the commands under Q&A but it didn't work for me. I am not sure if I'm doing it correctly.

**Comment by NeoEvaX** [comment]
Went through this today. Make sure to add:
`export PATH=$PATH:$HOME/go/bin`
to your .zshrc file. Then reload your terminal.

This seems to be the destination of `go install` files.

**Comment by adiguno** [comment]
This worked for me. 
Edit your .zshrc file:
```
# hot reload for go servers using air
path+=('~/go/bin')
alias air='~/go/bin/.air'
```

**Comment by DeniesKresna** [comment]
in my case, ".air" is not exist in go/bin instead "air" without dot.
just update above code to use
`alias air='~/go/bin/air'`
then its works for me.

**Comment by Alisalmasi** [comment]
> in my case, ".air" is not exist in go/bin instead "air" without dot. just update above code to use `alias air='~/go/bin/air'` then its works for me.

this worked for me , thanks.

**Comment by Kies8** [comment]
> in my case, ".air" is not exist in go/bin instead "air" without dot. just update above code to use `alias air='~/go/bin/air'` then its works for me.

this works also for me (macOS M1)

**Comment by ADTC** [comment]
Rather than adding an alias, I would reckon this is the more proper solution: `export PATH=$PATH:$HOME/go/bin`

Because in the future when you add other tools using `go install`, they would automatically benefit from it as well.
