### ISSUE TITLE
JOB HIRING!

### ISSUE THREAD

**Issue by cosmtrek** [cosmtrek/air#59]
I'm working at [Bytedance](https://www.bytedance.com) at present. There's a lot of open positions for hire. If you're interested, you can email me to know more. I'll follow up on your resume.

Referral:
* social: https://job.toutiao.com/s/7tH55d
* campus: https://job.toutiao.com/campus/  code: N2BZMNX

My info:
* email: cosmtrek@gmail.com
* wechat: cosmtrek

**Comment by xiantang** [comment]
bytedancer

**Comment by Hritik14** [comment]
Remote positions open ?

**Comment by cosmtrek** [comment]
@Hritik14 Nope...
