### ISSUE TITLE
air auto reboot occur error in window10+ go1.14.1+vscode

### ISSUE THREAD

**Issue by kindywu** [cosmtrek/air#62]
main.go has changed
building...        
failed to remove C:\WS\golang\gzcode\tmp\main.exe, error: remove **C:\WS\golang\gzcode\C:\WS\golang\gzcode\tmp\main.exe**: The filename, directory name, or volume label syntax is incorrect.
running...

![image](https://user-images.githubusercontent.com/6177365/78350567-ffe77a00-75d7-11ea-9c8b-1f30a7561b07.png)

**Comment by kindywu** [comment]
but it still work

**Comment by kindywu** [comment]
air is great!!!

**Comment by Slovty** [comment]
it can not work ,what about yours

**Comment by xiantang** [comment]
https://github.com/cosmtrek/air/pull/122 close
