### ISSUE TITLE
Config sample for windows

### ISSUE THREAD

**Issue by incker** [cosmtrek/air#65]
Have found [closed issue](https://github.com/cosmtrek/air/issues/34) about config sample for windows

But I am too green in golang so just simple coping does not work.

Can you provide please any working config that will just do `go run hello.go` for me, beginner or  `go run main.go` (Golang tutorial still haven't told me how to name main file)

**Comment by anpham1925** [comment]
hi @incker , i read in the doc, just run `curl -fLo air.exe https://git.io/windows_air` in your project for it to download air.exe to your project, then run it without any .air.conf file, im using that way and it can reload my app though there're some error or warning in console but it does reload the app

**Comment by incker** [comment]
@anpham1925, thank you, it works
