### ISSUE TITLE
[feature expect] support symbolic link

### ISSUE THREAD

**Issue by clintwan** [cosmtrek/air#69]
air is an awesome toy.
Actually I'm fresh player over 3 years until I meet air.

Here’s an advice.
I have a few symbolic links in my sources directory.
```
May 14 15:27:47 2020 go.mod
May 14 15:27:47 2020 go.sum
May 15 07:41:40 2020 main.go
Apr 30 11:00:30 2020 pb -> ../other-project/pb
Apr 25 09:59:06 2020 route
```

Hope air can imporve to support them like this
```
exclude_dir = ["pb"]
exclude_ext = ["pb/*.pb.go"]
```

**Comment by cosmtrek** [comment]
supported by https://github.com/cosmtrek/air/pull/137
