### ISSUE TITLE
Does not work on vscode remote WSL

### ISSUE THREAD

**Issue by vicnoah** [cosmtrek/air#72]
vscode remote WSL cannot monitor file changes

**Comment by oktayaa** [comment]
Can you explain a little bit more. I am using vscodium over SSHFS and it's working fine. Perhaps in your situation it's two layers of filesystems or something.

**Comment by vicnoah** [comment]
I am using ubuntu 20.04 subsystem on windows 10, and using vscode's remote wsl extension on the main system can't detect file changes during ubuntu subsystem development.Not sure if it can be fixed.

**Comment by apinprastya** [comment]
To make it work on WSL, you have to put your project inside root folder, ex: /home/{username}/golangproject
