### ISSUE TITLE
failed to remove in window10 vscode go1.14 The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by kindywu** [cosmtrek/air#78]
failed to remove C:\WS\golang\demo11\tmp\main.exe, error: remove **_C:\WS\golang\demo11\C:\WS\golang\demo11\tmp\main.exe:_** The filename, directory name, or volume label syntax is incorrect.

**Comment by kindywu** [comment]
mybe the path is double

**Comment by kindywu** [comment]
![image](https://user-images.githubusercontent.com/6177365/86310784-6caef680-bc51-11ea-93bc-1ae80855e7a5.png)

**Comment by kindywu** [comment]
the air code remove path is not 的log print path?
if err = os.Remove(cmdBinPath); err != nil {
	e.mainLog("failed to remove %s, error: %s", e.config.rel(e.config.binPath()), err)
}

**Comment by x199010** [comment]
source code/ runner/config.go
method binPath()
return filepath.Join(c.Root, c.Build.Bin)
to
return c.Build.Bin
(on windows)

**Comment by xiantang** [comment]
https://github.com/cosmtrek/air/pull/122 close
