### ISSUE TITLE
Overrides the text color that server might want to render

### ISSUE THREAD

**Issue by owais** [cosmtrek/air#8]
A basic hello world example of Gin with and without air

With air:

![image](https://user-images.githubusercontent.com/46186/38453880-9e3be72c-3a7a-11e8-9077-bcd9636da736.png)

Without air

![image](https://user-images.githubusercontent.com/46186/38453891-beb04f98-3a7a-11e8-8fe8-5f1bda1daeda.png)

**Comment by frederikhors** [comment]
Same story here, any news?

**Comment by cosmtrek** [comment]
I'm working on it. But it'll only work on Linux or macOS, Windows is not supported.

**Comment by cosmtrek** [comment]
@owais @frederikhors Hi, I've finished it and released a new version 1.10. Could you try this?

**Comment by frederikhors** [comment]
On Windows same problem also with v1.10.

**Comment by cosmtrek** [comment]
@frederikhors Yes, Windows is not supported now. The point is [pty](https://github.com/kr/pty) does not support Windows.

**Comment by cosmtrek** [comment]
The new version has fixed it.
