### ISSUE TITLE
Project Dead? 

### ISSUE THREAD

**Issue by udaya2899** [cosmtrek/air#86]
It's been more than a month since any updates were given, any issues were addressed and PR's merged.
I love air more than any other live-reload applications. Sad to see this :/

**Comment by cosmtrek** [comment]
Sorry to hear about it. I've been busy working recently and have no time to maintain it right now.

**Comment by aldovc** [comment]
@cosmtrek is it safe to assume this project is still active? Or should we start proposing alternatives? Thank you

**Comment by udaya2899** [comment]
It'll be great if you could allow volunteers to be maintainers. This is a good project, and I'd not want it to go unmaintained. people have been proposing good PR's

**Comment by cosmtrek** [comment]
Thanks for your kindness. I'll consider it and give feedback quickly.
