### ISSUE TITLE
how should i do when  /bin/sh: 1: go: not found happened?

### ISSUE THREAD

**Issue by kongerlengzi** [cosmtrek/air#93]
/bin/sh: 1: go: not found
[21:27:53] failed to build, error: exit status 127

**Comment by xiantang** [comment]
could you provide the minimum example for repoduce this bug.

**Comment by kongerlengzi** [comment]
> could you provide the minimum example for repoduce this bug.

i just go get it in go mod -->"go get github.com/cosmtrek/air", use comand  "air",show me "bash: /home/username/.air: no such file or directory.
so i  use "sudo air",them show me  "/bin/sh: 1: go: not found"

**Comment by xiantang** [comment]
add this `export PATH=$PATH:$(go env GOPATH)/bin ` to your`~/.bash_profile` and run air

**Comment by kongerlengzi** [comment]
> ~/.bash_profile

But,i did export  PATH=$PATH:$GOPATH/bin in my ~/.bashrc.It is ok for using golang command.Maybe my linux have some problem.Anyway,thank you for this.
