### ISSUE TITLE
please add install guide  Linux binary

### ISSUE THREAD

**Issue by uta-mori** [cosmtrek/air#97]

**Comment by xiantang** [comment]
this week we will release new version. and you can download binary in release page. we will add install guide in README page

**Comment by ksamborski** [comment]
I can't see any binary (only source code) on the release page. Could you add binaries there?

**Comment by tkms0106** [comment]
I guess only README is updated for the next version right now.
Therefore, they probably add it when the next version is released.

**Comment by xiantang** [comment]
@ksamborski @tkms0106  we will release next version in this weekend. and update guide in README

**Comment by xiantang** [comment]
@uta-mori @ksamborski @tkms0106  https://github.com/cosmtrek/air/releases/tag/v1.12.2 V1.12.2 is released you can download binary in release page and I will write install guide in README soon.

**Comment by xiantang** [comment]
now binary could download in release page.

**Comment by uta-mori** [comment]
@xiantang 

thanks

Could you put an example command in the README for the installation, just like the other methods?
